import { Alert, AlertStats, MetricsData } from '../types';

// Mock data for demo mode when backend is not available
export const mockAlerts: Alert[] = [
  {
    id: '1',
    alert_type: 'EARTHQUAKE',
    severity: 'CRITICAL',
    title: 'Major Earthquake Detected',
    description: 'A significant seismic event has been detected in the region. Immediate evacuation recommended for coastal areas.',
    latitude: 35.6762,
    longitude: 139.6503,
    location_name: 'Tokyo, Japan',
    country: 'JP',
    magnitude: 7.2,
    depth: 15.5,
    source: 'USGS',
    is_active: true,
    is_anomaly: true,
    acknowledged: false,
    event_time: new Date(Date.now() - 1800000).toISOString(),
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
  {
    id: '2',
    alert_type: 'STORM',
    severity: 'HIGH',
    title: 'Hurricane Warning',
    description: 'Category 4 hurricane approaching the coast. High winds and storm surge expected.',
    latitude: 25.7617,
    longitude: -80.1918,
    location_name: 'Miami, Florida',
    country: 'US',
    wind_speed: 145,
    source: 'NOAA',
    is_active: true,
    is_anomaly: false,
    acknowledged: false,
    event_time: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
  {
    id: '3',
    alert_type: 'FLOOD',
    severity: 'MEDIUM',
    title: 'Flash Flood Warning',
    description: 'Heavy rainfall causing flash flooding in low-lying areas. Avoid travel if possible.',
    latitude: 29.7604,
    longitude: -95.3698,
    location_name: 'Houston, Texas',
    country: 'US',
    rainfall: 45.5,
    source: 'NOAA',
    is_active: true,
    is_anomaly: false,
    acknowledged: true,
    event_time: new Date(Date.now() - 7200000).toISOString(),
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
  {
    id: '4',
    alert_type: 'EARTHQUAKE',
    severity: 'HIGH',
    title: 'Strong Earthquake Near Coast',
    description: 'Moderate to strong earthquake detected. Potential for aftershocks.',
    latitude: 36.2048,
    longitude: 138.2529,
    location_name: 'Nagano, Japan',
    country: 'JP',
    magnitude: 6.1,
    depth: 25.3,
    source: 'USGS',
    is_active: true,
    is_anomaly: false,
    acknowledged: false,
    event_time: new Date(Date.now() - 10800000).toISOString(),
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: false,
  },
  {
    id: '5',
    alert_type: 'STORM',
    severity: 'MEDIUM',
    title: 'Severe Thunderstorm Watch',
    description: 'Conditions favorable for severe thunderstorms with possible hail and strong winds.',
    latitude: 41.8781,
    longitude: -87.6298,
    location_name: 'Chicago, Illinois',
    country: 'US',
    wind_speed: 65,
    source: 'NOAA',
    is_active: true,
    is_anomaly: false,
    acknowledged: false,
    event_time: new Date(Date.now() - 14400000).toISOString(),
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: false,
    email_sent: true,
  },
  {
    id: '6',
    alert_type: 'FLOOD',
    severity: 'LOW',
    title: 'Minor Flooding Expected',
    description: 'Minor river flooding expected due to snowmelt. Monitor conditions.',
    latitude: 45.5017,
    longitude: -73.5673,
    location_name: 'Montreal, Canada',
    country: 'CA',
    rainfall: 12.5,
    source: 'Environment Canada',
    is_active: true,
    is_anomaly: false,
    acknowledged: false,
    event_time: new Date(Date.now() - 18000000).toISOString(),
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: false,
    email_sent: false,
  },
  {
    id: '7',
    alert_type: 'GENERAL',
    severity: 'LOW',
    title: 'Wildfire Risk Alert',
    description: 'High temperature and low humidity creating elevated wildfire risk.',
    latitude: 34.0522,
    longitude: -118.2437,
    location_name: 'Los Angeles, California',
    country: 'US',
    source: 'Cal Fire',
    is_active: true,
    is_anomaly: false,
    acknowledged: true,
    event_time: new Date(Date.now() - 21600000).toISOString(),
    created_at: new Date(Date.now() - 21600000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: false,
    email_sent: true,
  },
  {
    id: '8',
    alert_type: 'EARTHQUAKE',
    severity: 'MEDIUM',
    title: 'Moderate Seismic Activity',
    description: 'Multiple small earthquakes detected in the region. Monitor for larger events.',
    latitude: -33.4489,
    longitude: -70.6693,
    location_name: 'Santiago, Chile',
    country: 'CL',
    magnitude: 4.8,
    depth: 35.2,
    source: 'USGS',
    is_active: false,
    is_anomaly: false,
    acknowledged: true,
    event_time: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
  {
    id: '9',
    alert_type: 'STORM',
    severity: 'CRITICAL',
    title: 'Tornado Warning',
    description: 'Radar confirmed tornado on the ground. Take shelter immediately.',
    latitude: 35.4676,
    longitude: -97.5164,
    location_name: 'Oklahoma City, Oklahoma',
    country: 'US',
    wind_speed: 165,
    source: 'NOAA',
    is_active: true,
    is_anomaly: true,
    acknowledged: false,
    event_time: new Date(Date.now() - 2700000).toISOString(),
    created_at: new Date(Date.now() - 2700000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
  {
    id: '10',
    alert_type: 'FLOOD',
    severity: 'HIGH',
    title: 'Major River Flooding',
    description: 'Significant river flooding expected. Evacuations underway in flood-prone areas.',
    latitude: 30.4515,
    longitude: -91.1871,
    location_name: 'Baton Rouge, Louisiana',
    country: 'US',
    rainfall: 78.3,
    source: 'NOAA',
    is_active: true,
    is_anomaly: false,
    acknowledged: false,
    event_time: new Date(Date.now() - 5400000).toISOString(),
    created_at: new Date(Date.now() - 5400000).toISOString(),
    updated_at: new Date().toISOString(),
    sms_sent: true,
    email_sent: true,
  },
];

export const mockAlertStats: AlertStats = {
  total_alerts: 156,
  active_alerts: 42,
  alerts_by_severity: {
    CRITICAL: 8,
    HIGH: 15,
    MEDIUM: 32,
    LOW: 101,
  },
  alerts_by_type: {
    EARTHQUAKE: 45,
    STORM: 52,
    FLOOD: 38,
    GENERAL: 21,
  },
  recent_24h: 23,
  anomalies_detected: 5,
};

export const mockMetrics: MetricsData = {
  time_window_hours: 24,
  alerts: {
    total: 156,
    by_severity: {
      CRITICAL: 8,
      HIGH: 15,
      MEDIUM: 32,
      LOW: 101,
    },
    by_type: {
      EARTHQUAKE: 45,
      STORM: 52,
      FLOOD: 38,
      GENERAL: 21,
    },
  },
  events: {
    total: 892,
    by_type: {
      SEISMIC: 245,
      WEATHER: 412,
      HYDROLOGIC: 178,
      OTHER: 57,
    },
  },
  anomalies: {
    detected: 5,
  },
  predictions: {
    total: 28,
  },
  timestamp: new Date().toISOString(),
};
